### PR TITLE
windows support

### PR DESCRIPTION
**Pull request by yuval-k**

### CODE REVIEW

**Comment by vi** [comment]
Do current (without this patch) [cross-compiled builds for Windows](https://github.com/vi/nbdserve/releases) work already if you specify size of the device manually?

**Comment by yuval-k** [comment]
I didn't test the pre-combiled binaries, as i have a windows machine available. but they should as well, as long as you specify `--read-only`.

**Comment by vi** [comment]
Is writing problematic? Can it be fixed?

**Comment by yuval-k** [comment]
good question.. i couldn't get it to work with the rust api.
further exploration will probably require further fiddling with the rust api or using the windows api.

**Comment by vi** [comment]
Is it some bug of Rust's libstd?

Does it work in read-write mode if a file is specified as backing storage instead of a volume?

**Comment by yuval-k** [comment]
i dont think so, i think windows is touchy about physical devices
https://support.microsoft.com/en-us/help/100027/info-direct-drive-access-under-win32

**Comment by vi** [comment]
What in that article differenciates reading and writing?

**Comment by yuval-k** [comment]
good question - perhaps rust doesnt translate the flags correctly?
I can probably play around with this when I have some free time to see if i can make it work. my results are based on testing the runtime behaviour, and I didn't look on how the implementation was written.

**Pull request merged**
